export const SELLER_OPTION_GROUPS: Array<{ title: string; options: string[] }> = [
  {
    title: "Confort",
    options: [
      "Climatisation",
      "Climatisation automatique",
      "Climatisation bi-zone",
      "Climatisation tri-zone",
      "Sièges chauffants",
      "Sièges chauffants arrière",
      "Sièges ventilés",
      "Sièges massants",
      "Sièges réglages électriques avec mémoire",
      "Volant chauffant",
      "Volant réglable électroniquement",
      "Toit ouvrant / panoramique",
      "Vitres électriques",
      "Rétroviseurs électriques",
      "Rétroviseurs dégivrants",
      "Pare-brise chauffant",
      "Démarrage sans clé",
      "Accès sans clé",
      "Affichage tête haute",
      "Chargeur à induction",
    ],
  },
  {
    title: "Multimédia",
    options: [
      "GPS / Navigation",
      "Bluetooth",
      "USB",
      "Apple CarPlay",
      "Android Auto",
      "Écran tactile",
      "Système audio premium",
      "Audio système haut gamme",
    ],
  },
  {
    title: "Sécurité & Aides",
    options: [
      "ABS",
      "ESP/ESC",
      "Airbags",
      "Régulateur de vitesse",
      "Régulateur adaptatif",
      "Limiteur de vitesse",
      "Aide au maintien dans la voie",
      "Aide au stationnement automatique",
      "Alerte collision avant",
      "Surveillance angle mort",
      "Détection angles morts",
      "Détection piétons",
      "Alerte fatigue conducteur",
      "Capteurs de stationnement",
      "Caméra de recul",
      "Caméra 360°",
      "Détecteur de pluie",
      "Détecteur de luminosité",
      "Contrôle pression pneus (TPMS)",
    ],
  },
  {
    title: "Extérieur",
    options: [
      "Jantes alliage",
      "Feux LED",
      "Feux Matrix LED",
      "Feux laser",
      "Phares xénon",
      "Phares intelligents",
      "Barres de toit",
      "Crochet d'attelage",
      "Peinture nacrée",
      "Peinture mate",
      "Peinture métallisée",
    ],
  },
];

export const ALL_SELLER_OPTIONS = SELLER_OPTION_GROUPS.flatMap((g) => g.options);
